export default {
    //headerBackground: '#289fbf',
    headerBackground: '#059af7',
    headerText: '#ffffff',
    listItemBackground: '#ebe8e8',
    listItemText: '#080808',
    buttonBackground: '#059af7',
    buttonHighlight: '#5fb6ed',
    buttonText: '#ffffff',
    denyButtonBackground: '#de2121',
    denyButtonHighlight: '#fa7f7f',
    buttonSuccessBackground: '#00bd3f',
    buttonSuccessHighlight: '#69c789',
    selectedPointageBackground: '#ebe8e8',
    errorMessage: '#de2121',
    roundInputButtonsBackground: '#cccccc',
    roundShooterRowBackground: '#cccccc',
    roundShooterSelectedBorder: '#000000',
    roundZoneSelectedBorder: '#000000',
    roundShooterSelectedBackground: '#059af7',
    roundZoneSelectedBackground: '#059af7'
}